version: '3.6'

services:
  boxis-webapi:
    image: ekleziast56/boxis:latest
    volumes:
      - /docker-data/boxis/logs/webapi/:/app/logs
    environment:
      - ConnectionStrings:Boxis=Server=${POSTGRES_URL:-boxis-postgresdb};Port=5432;Database=${POSTGRES_DB:-boxis-db};User ID=${POSTGRES_USER:-boxis};Password=${POSTGRES_PASSWORD:-WBezCcZ6x6peWBj7};
    depends_on:
      - boxis-postgresdb
    restart: always

  boxis-client:
    image: ekleziast56/boxis-client:latest
    restart: always

  boxis-proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - /docker-data/boxis/logs/proxy/:/var/log/nginx 
      - ./nginx/boxis.conf:/etc/nginx/conf.d/default.conf    
      - ./nginx/boxis-upstreams/api.conf:/etc/nginx/conf.d/boxis-upstreams/api.conf
      - ./nginx/boxis-locations/api.conf:/etc/nginx/conf.d/boxis-locations/api.conf
      - ./nginx/boxis-upstreams/client.conf:/etc/nginx/conf.d/boxis-upstreams/client.conf
      - ./nginx/boxis-locations/client.conf:/etc/nginx/conf.d/boxis-locations/client.conf
    depends_on:
      - boxis-webapi
      - boxis-client
    restart: always

  boxis-postgresdb:
    build:
        context: ./postgres
        dockerfile: db.Dockerfile
    image: postgres
#    ports:
#       - "5432:5432"
    volumes:
      - /boxis-data/boxis/postgresdb:/var/lib/postgresdb
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-WBezCcZ6x6peWBj7}
      - POSTGRES_USER=${POSTGRES_USER:-boxis}
      - POSTGRES_DB=${POSTGRES_DB:-boxis-db}
    restart: always

volumes:
  boxis-data:
    driver: local