version: '3.6'

services:
  boxis-webapi:
    image: ekleziast56/boxis:latest
    volumes:
      - /docker-data/boxis/logs/webapi/:/app/logs
    environment:
      - ConnectionStrings:Boxis=Server=boxis-postgresdb;Port=5432;Database=${POSTGRES_DB};User ID=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
      - Auth__UserJwt__Issuer=${USERJWT_ISSUER:-Boxis.Api}
      - Auth__UserJwt__Audience=${USERJWT_AUDIENCE:-Boxis}
      - Auth__UserJwt__SecretKey=${USERJWT_SECRETKEY:-62039d6a-a515-4119-8dbe-7840cc2fc07c}
      - Auth__UserJwt__LifeTimeMinutes=${USERJWT_LIFETIMEMINUTES:-30}
      - ConfirmationCode__SecretKey=${CONFIRMATIONCODE_SECRETKEY:-0ef38915-2e32-4450-a514-44cd1e65621d}
      - ConfirmationCode__LifeTimeCodeInMinute=${CONFIRMATIONCODE_LIFETIMECODEINMINUTE:-30}
      - EmailService__SmtpServer=${EMAIL_SMTP_SERVER:-mail.nic.ru}
      - EmailService__FromAddress=${EMAIL_ADDRESS:-admin@boxis.io}
      - EmailService__Password=${{ secrets.EMAIL_PASSWORD }}
    depends_on:
      - boxis-postgresdb
    restart: always
    networks:
      - backend-network
      - postgres-network
      - frontend-network

  boxis-client:
    image: ekleziast56/boxis-client:latest
    restart: always
    networks:
      - frontend-network

  boxis-proxy:
    image: nginx:1.17.4-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /docker-data/boxis/logs/proxy/:/var/log/nginx
      - ./nginx/boxis.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/boxis-upstreams/api.conf:/etc/nginx/conf.d/boxis-upstreams/api.conf
      - ./nginx/boxis-locations/api.conf:/etc/nginx/conf.d/boxis-locations/api.conf
      - ./nginx/boxis-upstreams/client.conf:/etc/nginx/conf.d/boxis-upstreams/client.conf
      - ./nginx/boxis-locations/client.conf:/etc/nginx/conf.d/boxis-locations/client.conf
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on:
      - boxis-webapi
      - boxis-client
    restart: always
    networks: 
      - frontend-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot

  boxis-postgresdb:
    build:
        context: ./postgres
        dockerfile: db.Dockerfile
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/postgresql.conf:/var/lib/postgresql/boxis/data/postgresql.conf
      - boxis-pgdata:/var/lib/postgresql/boxis/data
      - boxis-pglogs:/var/log/postgresql/boxis
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/boxis-db
    restart: always
    networks:
      - postgres-network

volumes:
  boxis-data:
    driver: local
  boxis-pgdata:
    driver: local
  boxis-pglogs:
    driver: local

networks:
  backend-network:
  frontend-network:
  postgres-network: